version: 2.1

commands:
  setup_vyper:
    steps:
      - run:
          name: Install Python
          command: sudo apt install python3-pip
      - run:
          name: Install Vyper
          command: sudo pip install vyper
  pull_submodules:
    steps:
      - run:
          name: Pull submodules
          command: git submodule init && git submodule update
  install_dependencies:
    steps:
      - restore_cache:
          name: Restore NPM cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Save NPM cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

jobs:
  test:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - pull_submodules
      - install_dependencies
      - setup_vyper
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
