version: 2.1

commands:
  install_dependencies:
    steps:
      - restore_cache:
          name: Restore node modules
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Save node modules
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  test:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - install_dependencies
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
